; GENERATED by scripts/generate-markup-queries.js from queries/indents.scm
; — do not edit by hand.  highlights.scm and injections.scm are the only
; markup-specific query files and are maintained directly.

; Indentation queries for ucode.
; Capture names follow the nvim-treesitter standard.

; -------------------------------------------------------------------------
; Brace-delimited constructs — increase indent inside
; -------------------------------------------------------------------------

[
  (statement_block)
  (switch_body)
  (object)
  (array)
  (arguments)
  (formal_parameters)
] @indent.begin

; Closing delimiters — decrease indent
[
  "}"
  "]"
  ")"
] @indent.end

; -------------------------------------------------------------------------
; Alternative (colon/endif) syntax
; -------------------------------------------------------------------------

; The ':' after the condition opens the body
(if_alt_statement ":" @indent.begin)
(elif_clause ":" @indent.begin)
(for_alt_statement ":" @indent.begin)
(for_in_alt_statement ":" @indent.begin)
(while_alt_statement ":" @indent.begin)
(function_declaration ":" @indent.begin)

; Closing keywords close the body
[
  "endif"
  "endfor"
  "endwhile"
  "endfunction"
] @indent.end

; -------------------------------------------------------------------------
; Branch keywords (else/elif) — dedent keyword, indent following body
; -------------------------------------------------------------------------

(else_clause "else") @indent.branch
(else_alt_clause "else") @indent.branch
(elif_clause "elif") @indent.branch

; else_alt_clause has no ':' delimiter (grammar: 'else' repeat(statement)),
; so @indent.branch alone only dedents the 'else' keyword — it does not
; open an indent scope for the body. Add @indent.begin on the whole node
; so the body statements are indented one level relative to 'else'.
(else_alt_clause) @indent.begin

; -------------------------------------------------------------------------
; Switch
; -------------------------------------------------------------------------

(switch_case "case") @indent.branch
(switch_default "default") @indent.branch

; ── Markup-only alt-syntax spanning forms ─────────────────────────────
(if_alt_statement_tag ":" @indent.begin)
(for_alt_statement_tag ":" @indent.begin)
(for_in_alt_statement_tag ":" @indent.begin)
(while_alt_statement_tag ":" @indent.begin)
(function_alt_declaration ":" @indent.begin)

; ── Markup-only alt-syntax clause tags ────────────────────────────────
(elif_clause_tag "elif") @indent.branch @indent.begin
(else_alt_clause_tag "else") @indent.branch @indent.begin

; ── Markup-only brace-spanning forms ──────────────────────────────────
(if_statement_tag "{" @indent.begin)
(for_statement_tag "{" @indent.begin)
(for_in_statement_tag "{" @indent.begin)
(while_statement_tag "{" @indent.begin)
(function_declaration_tag "{" @indent.begin)
(try_statement_tag "{" @indent.begin)

; ── Markup-only brace-spanning clause tags ────────────────────────────
(elseif_clause_tag "else") @indent.branch @indent.begin
(else_clause_tag "else") @indent.branch @indent.begin
(catch_clause_tag "catch") @indent.branch @indent.begin
