/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE_PERCENT_DASH = 1,
  anon_sym_LBRACE_PERCENT = 2,
  anon_sym_DASH_PERCENT_RBRACE = 3,
  anon_sym_PERCENT_RBRACE = 4,
  anon_sym_LBRACE_LBRACE_DASH = 5,
  anon_sym_LBRACE_LBRACE = 6,
  anon_sym_DASH_RBRACE_RBRACE = 7,
  anon_sym_RBRACE_RBRACE = 8,
  anon_sym_LBRACE_POUND = 9,
  anon_sym_POUND_RBRACE = 10,
  sym__raw_text = 11,
  sym__stmt_code = 12,
  sym__expr_code = 13,
  sym__comment_body = 14,
  sym_document = 15,
  sym_statement_tag = 16,
  sym_expression_tag = 17,
  sym_comment_tag = 18,
  aux_sym_document_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_PERCENT_DASH] = "{%-",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [anon_sym_DASH_PERCENT_RBRACE] = "-%}",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_DASH_RBRACE_RBRACE] = "-}}",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_POUND] = "{#",
  [anon_sym_POUND_RBRACE] = "#}",
  [sym__raw_text] = "raw_text",
  [sym__stmt_code] = "code",
  [sym__expr_code] = "code",
  [sym__comment_body] = "comment_content",
  [sym_document] = "document",
  [sym_statement_tag] = "statement_tag",
  [sym_expression_tag] = "expression_tag",
  [sym_comment_tag] = "comment_tag",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_PERCENT_DASH] = anon_sym_LBRACE_PERCENT_DASH,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [anon_sym_DASH_PERCENT_RBRACE] = anon_sym_DASH_PERCENT_RBRACE,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_DASH_RBRACE_RBRACE] = anon_sym_DASH_RBRACE_RBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [sym__raw_text] = sym__raw_text,
  [sym__stmt_code] = sym__stmt_code,
  [sym__expr_code] = sym__stmt_code,
  [sym__comment_body] = sym__comment_body,
  [sym_document] = sym_document,
  [sym_statement_tag] = sym_statement_tag,
  [sym_expression_tag] = sym_expression_tag,
  [sym_comment_tag] = sym_comment_tag,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_PERCENT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt_code] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_code] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_body] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_close = 1,
  field_code = 2,
  field_content = 3,
  field_open = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_close] = "close",
  [field_code] = "code",
  [field_content] = "content",
  [field_open] = "open",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_close, 1},
    {field_open, 0},
  [2] =
    {field_close, 2},
    {field_code, 1},
    {field_open, 0},
  [5] =
    {field_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '%') ADVANCE(4);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '{') ADVANCE(1);
      if (lookahead == '}') ADVANCE(5);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '{') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(6);
      if (lookahead == '}') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == '}') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '}') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(15);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      if (lookahead == '-') ADVANCE(9);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH_PERCENT_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_DASH_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_DASH_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_POUND_RBRACE] = ACTIONS(1),
    [sym__raw_text] = ACTIONS(1),
    [sym__stmt_code] = ACTIONS(1),
    [sym__expr_code] = ACTIONS(1),
    [sym__comment_body] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(15),
    [sym_statement_tag] = STATE(2),
    [sym_expression_tag] = STATE(2),
    [sym_comment_tag] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACE_POUND] = ACTIONS(13),
    [sym__raw_text] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_statement_tag] = STATE(3),
    [sym_expression_tag] = STATE(3),
    [sym_comment_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACE_POUND] = ACTIONS(13),
    [sym__raw_text] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_statement_tag] = STATE(3),
    [sym_expression_tag] = STATE(3),
    [sym_comment_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(23),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(26),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(32),
    [anon_sym_LBRACE_POUND] = ACTIONS(35),
    [sym__raw_text] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(43), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(41), 5,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND,
  [12] = 2,
    ACTIONS(47), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(45), 5,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND,
  [24] = 2,
    ACTIONS(51), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(49), 5,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND,
  [36] = 2,
    ACTIONS(55), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(53), 5,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND,
  [48] = 2,
    ACTIONS(59), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(57), 5,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND,
  [60] = 2,
    ACTIONS(63), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(61), 5,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND,
  [72] = 2,
    ACTIONS(67), 1,
      sym__stmt_code,
    ACTIONS(65), 2,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_PERCENT_RBRACE,
  [80] = 2,
    ACTIONS(71), 1,
      sym__expr_code,
    ACTIONS(69), 2,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_RBRACE_RBRACE,
  [88] = 2,
    ACTIONS(73), 1,
      anon_sym_POUND_RBRACE,
    ACTIONS(75), 1,
      sym__comment_body,
  [95] = 1,
    ACTIONS(77), 2,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_PERCENT_RBRACE,
  [100] = 1,
    ACTIONS(79), 2,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_RBRACE_RBRACE,
  [105] = 1,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
  [109] = 1,
    ACTIONS(83), 1,
      anon_sym_POUND_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 12,
  [SMALL_STATE(6)] = 24,
  [SMALL_STATE(7)] = 36,
  [SMALL_STATE(8)] = 48,
  [SMALL_STATE(9)] = 60,
  [SMALL_STATE(10)] = 72,
  [SMALL_STATE(11)] = 80,
  [SMALL_STATE(12)] = 88,
  [SMALL_STATE(13)] = 95,
  [SMALL_STATE(14)] = 100,
  [SMALL_STATE(15)] = 105,
  [SMALL_STATE(16)] = 109,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_tag, 2, 0, 1),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_tag, 2, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_tag, 2, 0, 1),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_tag, 2, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_tag, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_tag, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_tag, 3, 0, 2),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_tag, 3, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_tag, 3, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_tag, 3, 0, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_tag, 3, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_tag, 3, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [81] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__raw_text = 0,
  ts_external_token__stmt_code = 1,
  ts_external_token__expr_code = 2,
  ts_external_token__comment_body = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__raw_text] = sym__raw_text,
  [ts_external_token__stmt_code] = sym__stmt_code,
  [ts_external_token__expr_code] = sym__expr_code,
  [ts_external_token__comment_body] = sym__comment_body,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__raw_text] = true,
    [ts_external_token__stmt_code] = true,
    [ts_external_token__expr_code] = true,
    [ts_external_token__comment_body] = true,
  },
  [2] = {
    [ts_external_token__raw_text] = true,
  },
  [3] = {
    [ts_external_token__stmt_code] = true,
  },
  [4] = {
    [ts_external_token__expr_code] = true,
  },
  [5] = {
    [ts_external_token__comment_body] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ucode_tmpl_external_scanner_create(void);
void tree_sitter_ucode_tmpl_external_scanner_destroy(void *);
bool tree_sitter_ucode_tmpl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ucode_tmpl_external_scanner_serialize(void *, char *);
void tree_sitter_ucode_tmpl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ucode_tmpl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ucode_tmpl_external_scanner_create,
      tree_sitter_ucode_tmpl_external_scanner_destroy,
      tree_sitter_ucode_tmpl_external_scanner_scan,
      tree_sitter_ucode_tmpl_external_scanner_serialize,
      tree_sitter_ucode_tmpl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ucode_tmpl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
