/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE_PERCENT_DASH = 1,
  anon_sym_LBRACE_PERCENT_PLUS = 2,
  anon_sym_LBRACE_PERCENT = 3,
  anon_sym_DASH_PERCENT_RBRACE = 4,
  anon_sym_PERCENT_RBRACE = 5,
  anon_sym_LBRACE_LBRACE_DASH = 6,
  anon_sym_LBRACE_LBRACE = 7,
  anon_sym_DASH_RBRACE_RBRACE = 8,
  anon_sym_RBRACE_RBRACE = 9,
  anon_sym_LBRACE_POUND_DASH = 10,
  anon_sym_LBRACE_POUND = 11,
  anon_sym_DASH_POUND_RBRACE = 12,
  anon_sym_POUND_RBRACE = 13,
  sym__raw_text = 14,
  sym__stmt_code = 15,
  sym__expr_code = 16,
  sym__comment_body = 17,
  sym_eof_close = 18,
  sym_document = 19,
  sym_statement_tag = 20,
  sym_expression_tag = 21,
  sym_comment_tag = 22,
  aux_sym_document_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_PERCENT_DASH] = "{%-",
  [anon_sym_LBRACE_PERCENT_PLUS] = "{%+",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [anon_sym_DASH_PERCENT_RBRACE] = "-%}",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_DASH_RBRACE_RBRACE] = "-}}",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_POUND_DASH] = "{#-",
  [anon_sym_LBRACE_POUND] = "{#",
  [anon_sym_DASH_POUND_RBRACE] = "-#}",
  [anon_sym_POUND_RBRACE] = "#}",
  [sym__raw_text] = "raw_text",
  [sym__stmt_code] = "code",
  [sym__expr_code] = "code",
  [sym__comment_body] = "comment_content",
  [sym_eof_close] = "eof_close",
  [sym_document] = "document",
  [sym_statement_tag] = "statement_tag",
  [sym_expression_tag] = "expression_tag",
  [sym_comment_tag] = "comment_tag",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_PERCENT_DASH] = anon_sym_LBRACE_PERCENT_DASH,
  [anon_sym_LBRACE_PERCENT_PLUS] = anon_sym_LBRACE_PERCENT_PLUS,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [anon_sym_DASH_PERCENT_RBRACE] = anon_sym_DASH_PERCENT_RBRACE,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_DASH_RBRACE_RBRACE] = anon_sym_DASH_RBRACE_RBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_POUND_DASH] = anon_sym_LBRACE_POUND_DASH,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [anon_sym_DASH_POUND_RBRACE] = anon_sym_DASH_POUND_RBRACE,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [sym__raw_text] = sym__raw_text,
  [sym__stmt_code] = sym__stmt_code,
  [sym__expr_code] = sym__stmt_code,
  [sym__comment_body] = sym__comment_body,
  [sym_eof_close] = sym_eof_close,
  [sym_document] = sym_document,
  [sym_statement_tag] = sym_statement_tag,
  [sym_expression_tag] = sym_expression_tag,
  [sym_comment_tag] = sym_comment_tag,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_PERCENT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt_code] = {
    .visible = true,
    .named = true,
  },
  [sym__expr_code] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_body] = {
    .visible = true,
    .named = true,
  },
  [sym_eof_close] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_statement_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_close = 1,
  field_code = 2,
  field_content = 3,
  field_open = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_close] = "close",
  [field_code] = "code",
  [field_content] = "content",
  [field_open] = "open",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_close, 1},
    {field_open, 0},
  [2] =
    {field_close, 2},
    {field_code, 1},
    {field_open, 0},
  [5] =
    {field_close, 2},
    {field_content, 1},
    {field_open, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '%') ADVANCE(4);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '{') ADVANCE(1);
      if (lookahead == '}') ADVANCE(5);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '%') ADVANCE(12);
      if (lookahead == '{') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '%') ADVANCE(7);
      if (lookahead == '}') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '}') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '}') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(17);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT_DASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT_PLUS);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      if (lookahead == '+') ADVANCE(11);
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DASH_PERCENT_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND_DASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      if (lookahead == '-') ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH_POUND_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 6},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT_PLUS] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_DASH_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_DASH_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND_DASH] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_DASH_POUND_RBRACE] = ACTIONS(1),
    [anon_sym_POUND_RBRACE] = ACTIONS(1),
    [sym__raw_text] = ACTIONS(1),
    [sym__stmt_code] = ACTIONS(1),
    [sym__expr_code] = ACTIONS(1),
    [sym__comment_body] = ACTIONS(1),
    [sym_eof_close] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(16),
    [sym_statement_tag] = STATE(2),
    [sym_expression_tag] = STATE(2),
    [sym_comment_tag] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT_PLUS] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACE_POUND_DASH] = ACTIONS(13),
    [anon_sym_LBRACE_POUND] = ACTIONS(15),
    [sym__raw_text] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym_statement_tag] = STATE(3),
    [sym_expression_tag] = STATE(3),
    [sym_comment_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT_PLUS] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(11),
    [anon_sym_LBRACE_POUND_DASH] = ACTIONS(13),
    [anon_sym_LBRACE_POUND] = ACTIONS(15),
    [sym__raw_text] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym_statement_tag] = STATE(3),
    [sym_expression_tag] = STATE(3),
    [sym_comment_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(25),
    [anon_sym_LBRACE_PERCENT_PLUS] = ACTIONS(25),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(28),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(34),
    [anon_sym_LBRACE_POUND_DASH] = ACTIONS(37),
    [anon_sym_LBRACE_POUND] = ACTIONS(40),
    [sym__raw_text] = ACTIONS(43),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(48), 3,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
    ACTIONS(46), 6,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_PERCENT_PLUS,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND_DASH,
  [14] = 2,
    ACTIONS(52), 3,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
    ACTIONS(50), 6,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_PERCENT_PLUS,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND_DASH,
  [28] = 2,
    ACTIONS(56), 3,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
    ACTIONS(54), 6,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_PERCENT_PLUS,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND_DASH,
  [42] = 2,
    ACTIONS(60), 3,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
    ACTIONS(58), 6,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_PERCENT_PLUS,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND_DASH,
  [56] = 2,
    ACTIONS(64), 3,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
    ACTIONS(62), 6,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_PERCENT_PLUS,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND_DASH,
  [70] = 2,
    ACTIONS(68), 3,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
    ACTIONS(66), 6,
      sym__raw_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_PERCENT_DASH,
      anon_sym_LBRACE_PERCENT_PLUS,
      anon_sym_LBRACE_LBRACE_DASH,
      anon_sym_LBRACE_POUND_DASH,
  [84] = 2,
    ACTIONS(72), 1,
      sym__stmt_code,
    ACTIONS(70), 3,
      sym_eof_close,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_PERCENT_RBRACE,
  [93] = 2,
    ACTIONS(76), 1,
      sym__expr_code,
    ACTIONS(74), 2,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_RBRACE_RBRACE,
  [101] = 2,
    ACTIONS(80), 1,
      sym__comment_body,
    ACTIONS(78), 2,
      anon_sym_DASH_POUND_RBRACE,
      anon_sym_POUND_RBRACE,
  [109] = 1,
    ACTIONS(82), 3,
      sym_eof_close,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_PERCENT_RBRACE,
  [115] = 1,
    ACTIONS(84), 2,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_RBRACE_RBRACE,
  [120] = 1,
    ACTIONS(86), 2,
      anon_sym_DASH_POUND_RBRACE,
      anon_sym_POUND_RBRACE,
  [125] = 1,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 14,
  [SMALL_STATE(6)] = 28,
  [SMALL_STATE(7)] = 42,
  [SMALL_STATE(8)] = 56,
  [SMALL_STATE(9)] = 70,
  [SMALL_STATE(10)] = 84,
  [SMALL_STATE(11)] = 93,
  [SMALL_STATE(12)] = 101,
  [SMALL_STATE(13)] = 109,
  [SMALL_STATE(14)] = 115,
  [SMALL_STATE(15)] = 120,
  [SMALL_STATE(16)] = 125,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_tag, 2, 0, 1),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_tag, 2, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_tag, 2, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_tag, 2, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_tag, 2, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_tag, 2, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement_tag, 3, 0, 2),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement_tag, 3, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_tag, 3, 0, 2),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_tag, 3, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_tag, 3, 0, 3),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_tag, 3, 0, 3),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [88] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__raw_text = 0,
  ts_external_token__stmt_code = 1,
  ts_external_token__expr_code = 2,
  ts_external_token__comment_body = 3,
  ts_external_token_eof_close = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__raw_text] = sym__raw_text,
  [ts_external_token__stmt_code] = sym__stmt_code,
  [ts_external_token__expr_code] = sym__expr_code,
  [ts_external_token__comment_body] = sym__comment_body,
  [ts_external_token_eof_close] = sym_eof_close,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__raw_text] = true,
    [ts_external_token__stmt_code] = true,
    [ts_external_token__expr_code] = true,
    [ts_external_token__comment_body] = true,
    [ts_external_token_eof_close] = true,
  },
  [2] = {
    [ts_external_token__raw_text] = true,
  },
  [3] = {
    [ts_external_token__stmt_code] = true,
    [ts_external_token_eof_close] = true,
  },
  [4] = {
    [ts_external_token__expr_code] = true,
  },
  [5] = {
    [ts_external_token__comment_body] = true,
  },
  [6] = {
    [ts_external_token_eof_close] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ucode_tmpl_external_scanner_create(void);
void tree_sitter_ucode_tmpl_external_scanner_destroy(void *);
bool tree_sitter_ucode_tmpl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ucode_tmpl_external_scanner_serialize(void *, char *);
void tree_sitter_ucode_tmpl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ucode_tmpl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ucode_tmpl_external_scanner_create,
      tree_sitter_ucode_tmpl_external_scanner_destroy,
      tree_sitter_ucode_tmpl_external_scanner_scan,
      tree_sitter_ucode_tmpl_external_scanner_serialize,
      tree_sitter_ucode_tmpl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ucode_tmpl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
